[#1] Set up base KMM base project
nimblehq/avishek-phong-kmm-ic pull request #16
Opened 2023-04-04 03:39 UTC by phongvhd93

- #1 

## What happened 👀

- Create a base project for KMM IC
- Update `CODEOWNER`
- Update `.gitignore
## Insight 📝

Create a base project for the team to work on the KMM IC. 

## Proof Of Work 📹

![Screenshot 2023-04-04 at 09 29 11](https://user-images.githubusercontent.com/22606906/229681104-ab07de16-c27c-4da6-8641-fa7c3610666f.png)

![Screenshot 2023-04-04 at 10 20 33](https://user-images.githubusercontent.com/22606906/229681133-c3857c31-3e95-4499-a93d-10734016cf34.png)

2023-04-05 02:56 UTC, AVI5HEK reviewed
We usually have a new line at the end of the file. But the auto-generated files don't have it. It might be very cumbersome to add a new line for each of these 22 files now. So how about we update these files whenever we work on them?

Also, any idea about the architecture and package management yet? Are we going to follow any template or sample codebase?

2023-04-05 02:56 UTC, AVI5HEK commented on shared/build.gradle.kts
> +        minSdk = 24
How about we use `21` as the min SDK? Hopefully, we'll never have to start a client project with this version in the future, but it'd be nice to have a working code in hand when needed. What do you think?

2023-04-10 02:42 UTC, markgravity commented on .github/CODEOWNERS
> +* @phongvhd93 @AVI5HEK
Please add me as code reviewer 🙏

2023-04-10 02:42 UTC, markgravity approved these changes

2023-04-12 06:08 UTC, suho requested changes

2023-04-12 06:08 UTC, suho commented on iosApp/Podfile
@phongvhd93 Please check all files that are missing the new line at the end of the file

2023-04-12 06:35 UTC, phongvhd93 commented on iosApp/Podfile
I solved all the missing blank line at EOF

2023-04-12 07:27 UTC, suho approved these changes

2023-04-12 14:29 UTC, merged