[#2] [Chore
nimblehq/avishek-phong-kmm-ic pull request #27
Opened 2023-04-06 02:33 UTC by phongvhd93

- Close #2 

## What happened 👀

- Use the iOS chapter template to generate an iOS application in `iosApp` folder.
- Set up provisioning profile and match configuration.
- Set stating bundle id and production bundle id

## Insight 📝

To keep the iOS project consistent with the project structure the iOS chapter is using, I replaced the default application generated by AndroidStudio with the project, which is generated by the iOS chapter's ios-template

## Proof Of Work 📹

https://user-images.githubusercontent.com/22606906/230257504-34c93c79-0bb8-4df8-8512-ed04845a6e75.mp4

2023-04-10 02:44 UTC, markgravity approved these changes

2023-04-12 07:55 UTC, suho requested changes

2023-04-12 07:55 UTC, suho commented on iosApp/.sourcery.yml
> +    - RxSwift
Please remove RxSwift and RxCocoa

2023-04-12 07:55 UTC, suho commented on iosApp/LICENSE
> +MIT License
Please remove this file

2023-04-12 07:55 UTC, suho commented on iosApp/PhongKMMIC/Configurations/Plists/Info.plist
> +	<string>APPL</string>
is it expected to change to `APPL` 🤔

2023-04-12 07:55 UTC, suho commented on iosApp/PhongKMMIC/Sources/Application/AppDelegate.swift
> +        let homeViewController = HomeViewController()
If you are setting the project with SwiftUI, please remove these setup

2023-04-12 07:55 UTC, suho commented on iosApp/deliverable_setup.sh
> +#!/bin/sh
Please remove this file

2023-04-13 07:12 UTC, markgravity approved these changes

2023-04-13 10:05 UTC, suho approved these changes

2023-04-14 02:07 UTC, merged